# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 17:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='El tel\xe9fono debe empezar por 6, 7 \xf3 9, y estar compuesto por 9 d\xedgitos', regex='^[9|6|7][0-9]{8}$')])),
                ('email', models.EmailField(max_length=254)),
                ('vehicle_type', models.CharField(choices=[('TUR', 'Turismo'), ('ALL', 'Todo terreno'), ('COM', 'Comercial')], max_length=3)),
                ('vehicle', models.CharField(max_length=9)),
                ('call_preference', models.CharField(choices=[('MON', 'Ma\xf1ana'), ('AFT', 'Tarde'), ('NIG', 'Noche')], max_length=3)),
            ],
        ),
    ]
